### ISSUE TITLE
[ Feature ] - proma_backend 도메인 설계

### ISSUE THREAD

**Issue by aeeengsungwoo** [PROMAplatform/Proma_back#3]
## 🛠️ 계획된 개발 기능
ERD Cloud에 설계된 테이블을 기반으로 Spring JPA 엔티티 클래스 구현

## 🛠 기능 구현 세부사항
ERD Cloud에서 설계된 테이블 구조를 분석하고, 각 테이블에 해당하는 엔티티 클래스를 생성합니다.
엔티티 클래스 간의 관계를 JPA 어노테이션(OneToMany, ManyToOne)을 사용하여 매핑합니다.
엔티티 클래스의 필드에 적절한 데이터 타입, 제약 조건(nullable, unique 등)을 설정합니다.

## 📝 check-lists
- [x] ERD Cloud 테이블 분석 완료
- [x] 엔티티 클래스 생성 완료
- [x] 엔티티 간 관계 매핑 완료
- [x] 엔티티 필드 및 제약 조건 설정 완료

**Comment by park20011029** [comment]
LGTM
